name: kidburg_banquet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  excel: ^4.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  meta: ^1.10.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/template_banquet.xlsx
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/kidburg_launch_icon.png"
  min_sdk_android: 21