name: kidburg_banquet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  excel: ^4.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  build_runner: ^2.4.9
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.10.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  device_info_plus: ^10.1.2
  http: ^1.2.0
  uuid: ^4.4.2
  file_picker: ^8.1.2
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    
flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/kidburg_launch_icon.png"
  min_sdk_android: 21

# После обновление на новую версию флаттер
# без этого колхоза выходит ошибка и не
# запускается приложение на эмуляторе
dependency_overrides:
  archive: ^3.6.1